# Header
author: dnhyxc

menu:
  home: /
  article: /archives
  informal: /tags
  about: /about

# SubNav
subnav:
  # wechat: "dnh20091206"
  # mail: "2640559435@qq.com"
  juejin: "https://juejin.cn/user/4265760848885368"
  github: "https://github.com/dnhyxc"
  zhihu: "https://www.zhihu.com/people/xia-mo-65-57-25/collections"
  # qq: "2640559435"
  # weibo: "#"
  # rss: "#"
  # douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
# excerpt_link: 阅读全文
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
baidu_tongji: true
google_analytics: true

favicon: http://7xkj1z.com1.z0.glb.clouddn.com/head.jpg

#你的头像url
avatar: https://avatars.githubusercontent.com/u/57223903?s=460&u=6af037d861ac65ffc7916d60edbe0c541d1cc9d3&v=4

#是否开启分享
share: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  dnhyxc: https://github.com/dnhyxc
#是否开启“关于我”。
# 不开启——
aboutme: false
#开启——
# aboutme:

swift_search:
  enable: true

busuanzi:
  enable: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: "谢谢你请我吃糖果"
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin:
